language: scala
scala:
  - 2.12.10
jdk:
  - oraclejdk8
  - openjdk8
addons:
  hosts:
    - sbt-docker-ci
  hostname: sbt-docker-ci
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
